# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  ParameterListWrapping:
    indentSize: 2

complexity:
  LongParameterList:
    active: false
